### ISSUE TITLE
Could multiple lines added to the generated code throw this off?

### ISSUE THREAD

**Issue by jedwards1211** [evanw/node-source-map-support#103]

**Comment by jeffschmitz** [comment]
Did you ever get resolution on this?  I'm seeing the same error now.

**Comment by jedwards1211** [comment]
No, I stopped loading `source-map-support/register` with a Webpack banner and just put it in the Webpack entry instead, and I'm not having issues anymore

**Comment by basarat** [comment]
I am getting the same error but with `ts-node` + `mocha`: 

```
MOCHA STDERR: D:\REPOS\alm\node_modules\source-map-support\source-map-support.js:411
      var hasStack = (arguments[1] && arguments[1].stack);
                                                  ^

TypeError: Column must be greater than or equal to 0, got -62
    at SourceMapConsumer_findMapping [as _findMapping] (D:\REPOS\alm\node_modules\source-map-support\node_modules\source-map\lib\source-map\source-map-consumer.js:281:15)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (D:\REPOS\alm\node_modules\source-map-support\node_modules\source-map\lib\source-map\source-map-consumer.js:310:26)
    at mapSourcePosition (D:\REPOS\alm\node_modules\source-map-support\source-map-support.js:188:42)
    at wrapCallSite (D:\REPOS\alm\node_modules\source-map-support\source-map-support.js:327:20)
    at D:\REPOS\alm\node_modules\source-map-support\source-map-support.js:362:26
    at Array.map (native)
    at Function.prepareStackTrace (D:\REPOS\alm\node_modules\source-map-support\source-map-support.js:361:24)
    at process.emit (D:\REPOS\alm\node_modules\source-map-support\source-map-support.js:411:51)
    at process._fatalException (node.js:237:26)
```
