### ISSUE TITLE
Doesn't work with babel-register

### ISSUE THREAD

**Issue by dangreen** [evanw/node-source-map-support#121]
```
require("babel-register")();

require("./test.js");
```

test.js:
```
require("source-map-support").install();
throw new Error('test');
```

error:
```
throw new Error('test');
^

Error: test
    at Object.<anonymous> (/Users/dangreen/github/jam-editor/jam-server/test.js:4:7)
    at Module._compile (module.js:425:26)
    at loader (/Users/dangreen/github/jam-editor/jam-server/node_modules/babel-register/lib/node.js:131:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dangreen/github/jam-editor/jam-server/node_modules/babel-register/lib/node.js:141:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dangreen/github/jam-editor/jam-server/smtest.reg.js:3:1)
    at Module._compile (module.js:425:26)
```

Compiled code:
```
"use strict";

require("source-map-support").install();
throw new Error('test');
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNtdGVzdC5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOztBQUFBLE9BQU8sQ0FBQyxvQkFBb0IsQ0FBQyxDQUFDLE9BQU8sRUFBRSxDQUFDO0FBQ3hDLE1BQU0sSUFBSSxLQUFLLENBQUMsTUFBTSxDQUFDLENBQUMiLCJmaWxlIjoic210ZXN0LmpzIiwic291cmNlc0NvbnRlbnQiOlsicmVxdWlyZShcInNvdXJjZS1tYXAtc3VwcG9ydFwiKS5pbnN0YWxsKCk7XG50aHJvdyBuZXcgRXJyb3IoJ3Rlc3QnKTsiXX0=
```

**Comment by wmertens** [comment]
You need to register the source map support before babel register…

**Comment by dangreen** [comment]
@wmertens mmmm how ? example ?

**Comment by dangreen** [comment]
```
require("source-map-support").install();
require("babel-register")();

require("./test.js");
```

and all works. I think developers should write some about it in documentation.

**Comment by tamlyn** [comment]
Oh wow, I spent all of yesterday trying to work this out! Any chance of adding it to the readme?

**Comment by dangreen** [comment]
@tamlyn I'm sorry I made a mistake. See working with babel [here](https://github.com/sane/sails-hook-babel/blob/master/index.js#L43).

**Comment by graingert** [comment]
@tamlyn how is it done without sails?

**Comment by graingert** [comment]
fyi, babel-register includes support for source-map-support directly. https://github.com/babel/babel/blob/dc1f40540de11045bb4714350350e012fee4f93e/packages/babel-register/src/node.js#L11-L24
