### ISSUE TITLE
Latest release causes TypeError: Cannot read property 'generatedLine' of undefined

### ISSUE THREAD

**Issue by madole** [evanw/node-source-map-support#150]
```
TypeError: Cannot read property 'generatedLine' of undefined
      at compareByGeneratedPositionsDeflated (node_modules/source-map-support/node_modules/source-map/lib/util.js:344:46)
      at doQuickSort (node_modules/source-map-support/node_modules/source-map/lib/quick-sort.js:88:11)
      at exports.quickSort (node_modules/source-map-support/node_modules/source-map/lib/quick-sort.js:113:3)
      at SourceMapConsumer_parseMappings [as _parseMappings] (node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js:519:5)
      at SourceMapConsumer.Object.defineProperty.get (node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js:68:12)
      at SourceMapConsumer_originalPositionFor [as originalPositionFor] (node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js:606:11)
      at mapSourcePosition (node_modules/source-map-support/source-map-support.js:188:42)
      at wrapCallSite (node_modules/source-map-support/source-map-support.js:327:20)
      at node_modules/source-map-support/source-map-support.js:362:26
      at Array.map (native)
      at Function.prepareStackTrace (node_modules/source-map-support/source-map-support.js:361:24)
```

**Comment by LinusU** [comment]
@tomhughes @johnjbarton any ideas?

**Comment by tomhughes** [comment]
It's hard to see how it can come directly from my changes in #124 as the only change I made to the source-map-support code was to ensure a string was coerced to a number.

So most likely it's the update of the underlying source-map module that has triggered it, or some other change in source-map-support.
