### ISSUE TITLE
Issue somewhere between 0.4.2 and 0.4.5: ModuleNotFoundError: Module not found

### ISSUE THREAD

**Issue by lmeyerov** [evanw/node-source-map-support#153]
Our use of node-source-map-support works in node 6, but issues in node 0.10, and seems to be related to the recent changes. Downgrading from 0.4.5 to 0.4.2 eliminates errors like the below.

There have been surprisingly big changes on 0.4.x recently: I recommend reverting those and moving them to 0.5.x .

```

ModuleNotFoundError: Module not found: Error: Cannot resolve module 'module' in /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:31:26)
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:28:12
    at Storage.finished (/Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/polyfills.js:264:29
    at Object.oncomplete (fs.js:108:15)
resolve module module in /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support
  looking for modules in /Users/lmeyerov/Desktop/work/central/node_modules
    /Users/lmeyerov/Desktop/work/central/node_modules/module doesn't exist (module as directory)
    resolve 'file' module in /Users/lmeyerov/Desktop/work/central/node_modules
      resolve file
        /Users/lmeyerov/Desktop/work/central/node_modules/module doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/module.json doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/module.js doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/module.jsx doesn't exist
  looking for modules in /Users/lmeyerov/node_modules
    /Users/lmeyerov/node_modules/module doesn't exist (module as directory)
    resolve 'file' module in /Users/lmeyerov/node_modules
      resolve file
        /Users/lmeyerov/node_modules/module.json doesn't exist
        /Users/lmeyerov/node_modules/module doesn't exist
        /Users/lmeyerov/node_modules/module.js doesn't exist
        /Users/lmeyerov/node_modules/module.jsx doesn't exist
  looking for modules in /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules
    /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/module doesn't exist (module as directory)
    resolve 'file' module in /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules
      resolve file
        /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/module doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/module.json doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/module.js doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/node_modules/module.jsx doesn't exist
  looking for modules in /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support/node_modules
    /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support/node_modules/module doesn't exist (module as directory)
    resolve 'file' module in /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support/node_modules
      resolve file
        /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support/node_modules/module doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support/node_modules/module.json doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support/node_modules/module.js doesn't exist
        /Users/lmeyerov/Desktop/work/central/node_modules/source-map-support/node_modules/module.jsx doesn't exist
npm ERR! Darwin 13.3.0
npm ERR! argv "/Users/lmeyerov/.nvm/v0.10.46/bin/node" "/Users/lmeyerov/.nvm/v0.10.46/bin/npm" "run" "build"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! StreamGL@0.2.0 build: `npm run clean && webpack --config ./webpack/webpack.prod.config.js --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the StreamGL@0.2.0 build script 'npm run clean && webpack --config ./webpack/webpack.prod.config.js --bail'.
npm ERR! This is most likely a problem with the StreamGL package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && webpack --config ./webpack/webpack.prod.config.js --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs StreamGL
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls StreamGL
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lmeyerov/Desktop/work/central/node_modules/graph-viz/node_modules/StreamGL/npm-debug.log
npm ERR! Darwin 13.3.0
npm ERR! argv "/Users/lmeyerov/.nvm/v0.10.46/bin/node" "/Users/lmeyerov/.nvm/v0.10.46/bin/npm" "install"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! StreamGL@0.2.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the StreamGL@0.2.0 postinstall script 'npm run build'.
npm ERR! This is most likely a problem with the StreamGL package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs StreamGL
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls StreamGL
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lmeyerov/Desktop/work/central/npm-debug.log
```

**Comment by jknight12882** [comment]
Also experiencing the same issue when building using `webpack`

**Comment by lizell** [comment]
The latest version that still works is `0.4.3`. The `module` dependency that breaks things seems to be added at https://github.com/evanw/node-source-map-support/commit/2369eea005da0bce5c831a51f937867261160506

**Comment by LinusU** [comment]
Shouldn't that only happen if `hookRequire` is set to true though? Are you using `hookRequire`?

**Comment by lizell** [comment]
No, not to my knowledge. From the code:
```js
require('source-map-support').install();
```

**Comment by kpdecker** [comment]
Webpack resolves are done at build time, so the flag won't be helpful here. I don't ha e docs in front of me right now, but quick fix would be to alias module in the webpack config or I believe there may be options to avoid importing modules with a given name.

Longer term fixes to try:
- try block MIGHT make webpack happy
- have a browser targeted target and use the browser package.json key to enforce resolution of this.

I'll try to take a look but this might not be until the weekend.

**Comment by shri3k** [comment]
Just to add to @jknight12882's comment I also get this in `webpack` (which has babel) but in `production` build only which makes sense cause `babel-register` depends on this package and `babel-register` is "dev dependency" for `babel`.
