### ISSUE TITLE
No line number visible on standard input

### ISSUE THREAD

**Issue by nickbreaton** [evanw/node-source-map-support#178]
Below is the source file I am using:

```js
require('source-map-support').install();
throw new Error('error on line two');
```

The following command will generate the __correct__ output:

```sh
node dist/bundle.js
```

output:

```
/Users/nick/Desktop/dist/webpack:/example/index.js:2
throw new Error('error on line two');
^
Error: error on line two
    at Object.<anonymous> (/Users/nick/Desktop/dist/webpack:/example/index.js:2:1)
    at __webpack_require__ (/Users/nick/Desktop/dist/webpack:/webpack/bootstrap 8d9d0b53441c2ea13b08:19:1)
    at /Users/nick/Desktop/dist/webpack:/webpack/bootstrap 8d9d0b53441c2ea13b08:39:1
    at Object.<anonymous> (/Users/nick/Desktop/dist/bundle.js:43:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

The following command with __not__ generate a line number or other source map information:

```sh
cat dist/bundle.js | node
```

output:

```
Error: error on line two
    at Object.<anonymous> ([stdin]:48:8)
    at __webpack_require__ ([stdin]:20:30)
    at [stdin]:40:18
    at [stdin]:43:10
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:571:32)
    at Immediate.<anonymous> (bootstrap_node.js:387:29)
    at runCallback (timers.js:651:20)
```

The issue seems to arise when passing a script via standard input to node. I originally discovered it when I was creating a child process in node and passing generated code to it.

Please let me know if any more information is needed.

Thank you for your time in supporting this awesome project, and for taking the time to help me.

**Comment by chrisnicola** [comment]
Ran into this problem as well. Same problem with `node -e` with a code string.

**Comment by fvictorio** [comment]
Hi, sorry for the bump, but I ran into this too and I can't think of a workaround.

Is this a hard fix? Any way I could help?

**Comment by davidpomerenke** [comment]
Can confirm this. Do you think it is a bug with `node-source-map-support` or with `node`?

@fvictorio I think the workaround is simple:

Instead of
```bash
cat src | ... | node --require source-map-support/register
``` 
use
```bash
cat src | ... > tmp.js && node --require source-map-support/register tmp.js && rm tmp.js
```
or
```bash
cat src | ... > tmp.mjs && node --require source-map-support/register tmp.mjs && rm tmp.mjs
```
