### ISSUE TITLE
An error is thrown while trying to get call stack

### ISSUE THREAD

**Issue by justinmchase** [evanw/node-source-map-support#210]
I'm just calling:
```js
err.stack
```
And getting this error:
```
TypeError: Column must be greater than or equal to 0, got -1
    at SourceMapConsumer_findMapping [as _findMapping] (/var/task/node_modules/mya-input-shared/node_modules/source-map/lib/source-map-consumer.js:588:13)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/var/task/node_modules/mya-input-shared/node_modules/source-map/lib/source-map-consumer.js:653:22)
    at mapSourcePosition (/var/task/node_modules/mya-input-shared/node_modules/source-map-support/source-map-support.js:213:42)
    at mapEvalOrigin (/var/task/node_modules/mya-input-shared/node_modules/source-map-support/source-map-support.js:236:20)
    at wrapCallSite (/var/task/node_modules/mya-input-shared/node_modules/source-map-support/source-map-support.js:373:14)
    at /var/task/node_modules/mya-input-shared/node_modules/source-map-support/source-map-support.js:392:26
    at Array.map (native)
    at Function.prepareStackTrace (/var/task/node_modules/mya-input-shared/node_modules/source-map-support/source-map-support.js:391:24)
    at TypeError.get stack [as stack] (native)
    at Object.error (/var/task/node_modules/mya-input-shared/lib/lib/log.js:26:16)
```

This is a pretty intermittent bug, most of my errors are having their stacks correctly mapped. I'm guessing there is a bug in the source map itself, but regardless I would expect this to not throw an error here but instead just return the original call stack at least. 

My work around is to just catch the error and ignore it for now, because this is happening while trying to log a different error. Any other workarounds or suggestions?

**Comment by LinusU** [comment]
> [...] but regardless I would expect this to not throw an error here but instead just return the original call stack at least.

Hmm, personally I'm not a fan of just hiding errors.

> I'm guessing there is a bug in the source map itself [...]

If this is the case, I don't think it's that bad to throw an error 🤔

**Comment by justinmchase** [comment]
The problem is, this was in my global error handler. Throwing an unrelated error while trying to handle and display unhandled erorrs and then throwing another error really sucks.

**Comment by justinmchase** [comment]
I definitely think this should be a best effort kind of a tool and should not throw any exceptions. If you disagree feel free to close, that's just my $0.02
