### ISSUE TITLE
frame.getFileName is not a function on Node 10 for Babel-compiled code

### ISSUE THREAD

**Issue by AndreyBelym** [evanw/node-source-map-support#213]
Looks like `source-map-support` can't handle exceptions in Babel-compiled modules with inlined source maps on Node 10. 
E.g. I created a simple module that throws an error:
```
throw new Error('123');
```

Then I compiled it with Babel API, using the following configuration:
```
{
            passPerPreset: true,
            presets: [presetEnv],
            filename: filename,
            retainLines: true,
            sourceMaps: 'inline',
            ast: false,
            babelrc: false,
            highlightCode: false
}
```

and got the following result:
```
'use strict';throw new Error('123');
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3QuanMiXSwibmFtZXMiOlsiRXJyb3IiXSwibWFwcGluZ3MiOiJhQUFBLE1BQU0sSUFBSUEsS0FBSixDQUFVLEtBQVYsQ0FBTiIsImZpbGUiOiJ0ZXN0LmpzIiwic291cmNlc0NvbnRlbnQiOlsidGhyb3cgbmV3IEVycm9yKCcxMjMnKTsiXX0=
```

Then I created a simple script that installs `source-map-support` and tries to require compiled module:
```
const sourceMapSupport = require('source-map-support');

sourceMapSupport.install();

require('./module.compiled')
```

On Node 8.4.0 I have correct error message and stack:
```
Error: 123
    at Object.<anonymous> (/Users/testcafe/testcafe/test.js:1:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
```

On Node 10 I have the following error somewhere in `source-map-support`:
```
TypeError: frame.getFileName is not a function
    at /Users/testcafe/testcafe/node_modules/source-map-support/source-map-support.js:53:24
    at mapSourcePosition (/Users/testcafe/testcafe/node_modules/source-map-support/source-map-support.js:171:21)
    at wrapCallSite (/Users/testcafe/testcafe/node_modules/source-map-support/source-map-support.js:343:20)
```

**Comment by AndreyBelym** [comment]
Sorry, I used `v0.4.18`. IT's fixed in `0.5.5`.
