### ISSUE TITLE
Node 12 "async" annotations are lost when using this package

### ISSUE THREAD

**Issue by alcuadrado** [evanw/node-source-map-support#243]
Node 12 added some limited support for async stack traces. I'm impressed that this package supports them, but it removes a useful annotation from them:

Given this file:

```js
function p() {
  return new Promise(resolve => setTimeout(resolve, 0))
}

async function f() {
  await p()
  throw Error("")
}

async function main() {
  await f()
}

main()
  .catch(console.error)
```

The stack traces without registering `source-map-support` is:

```
Error
    at f (/private/tmp/async-stack-traces/index.js:9:9)
    at async main (/private/tmp/async-stack-traces/index.js:13:3)
```

With `source-map-support` registered is:

```
Error:
    at f (/private/tmp/async-stack-traces/index.js:9:9)
    at main (/private/tmp/async-stack-traces/index.js:13:3)
```

I think the `async` annotation there is useful, as this stack trace is not the actual one as seen by v8, but an augmented one.

**Comment by justinmchase** [comment]
Can confirm, this is super confusing as I wasn't sure what was causing it and I wasn't sure if my stack traces were actually working. Several hours later I found this issue.

**Comment by LinusU** [comment]
Would love a PR addressing this 🚀

**Comment by cspotcode** [comment]
To fix this, the implementation of `CallSiteToString` -- which is copy-pasted from V8 source code -- must be updated to match the latest V8 implementation.
