### ISSUE TITLE
TypeError: Cannot read property 'String' of undefined

### ISSUE THREAD

**Issue by KazimirPodolski** [evanw/node-source-map-support#306]
Using `ts-node-dev` with `source-map-support` 0.5.19 breaks [Nylas SDK](https://github.com/nylas/nylas-nodejs/issues/323):

```
TypeError: Cannot read property 'String' of undefined
    at /usr/src/project/node_modules/nylas/lib/models/restful-model.js:130:34
    at Object.<anonymous> (/usr/src/project/node_modules/nylas/lib/models/restful-model.js:145:2)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/usr/src/project/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.nodeDevHook [as .js] (/usr/src/project/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
```

This is all information I get while starting the server with `ts-node-dev`. Looking at restful-model.js:130 I don't see anything related to the error. Is there any way to find out what went wrong?

**Comment by KazimirPodolski** [comment]
https://github.com/wclr/ts-node-dev/issues/185
