### ISSUE TITLE
Use with mocha

### ISSUE THREAD

**Issue by tinganho** [evanw/node-source-map-support#45]
I'm trying to use your library with mocha. But I don't get it to work. I use Typescript and compile with source map support. And I require your library and install it as said in the docs before I run the mocha command.

**Comment by evanw** [comment]
It works for me:

```
$ cat > test.ts
declare var require, it;
require('source-map-support').install();
it('xxx', () => { throw new Error('yyy'); });
$ tsc --sourceMap test.ts && mocha

  ․

  0 passing (6ms)
  1 failing

  1)  xxx:
     Error: yyy
      at Context.<anonymous> (test.ts:3:25)
      at callFn (runnable.js:223:21)
      at Test.Runnable.run (runnable.js:216:7)
      at Runner.runTest (runner.js:374:10)
      at runner.js:452:12
      at next (runner.js:299:14)
      at runner.js:309:7
      at next (runner.js:247:23)
      at Object._onImmediate (runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:345:15)
```

The source file in the stack trace is "test.ts" as expected.

**Comment by tinganho** [comment]
@evanw this is my code
```typescript
/// <reference path="../typings/mocha/mocha.d.ts"/>
/// <reference path="../typings/chai/chai.d.ts"/>
/// <reference path="../typings/source-map-support/source-map-support.d.ts"/>

import * as sourceMap from 'source-map-support'
sourceMap.install()
it('xxx', () => { throw new Error('yyy'); });
```
```
  0 passing (6ms)
  1 failing

  1)  xxx:
     Error: yyy
      at Context.<anonymous> (/Users/tinganho/Development/CSM/build-test/index.js:3:31)
      at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:221:32)
      at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by tinganho** [comment]
Ok It was mapRoot option that cause this issue.
