### ISSUE TITLE
Stack trace URls not clickable

### ISSUE THREAD

**Issue by aldendaniels** [evanw/node-source-map-support#72]
As noted in https://github.com/petkaantonov/bluebird/issues/363, the `file:line-number` entries in the error stack trace generated by `souce-map-support` are not clickable in Chrome.

This is because `source-map-support` is generating:
```
Unhandled rejection Error: oops!
    at Route.willTransitionTo [as onEnter] (components/outcomes-component.js:29:21)
```

Instead of:
```
Unhandled rejection Error: oops!
    at Route.willTransitionTo [as onEnter] (http://localhost:8080/components/outcomes-component.js:29:21)
```

Prefixing the paths with the page origin should solve the problem.

**Comment by guncha** [comment]
I'm seeing something similar - regular javascript files get the URL appended, so the link works, but source mapped files do not.
